# Reference: https://en.wikipedia.org/wiki/Periodic_table_(large_cells)


[atoms.HYDROGEN]
number = 1
mass = 1.008
symbol = "H"
name = "hydrogen"
group = 1
diatomic = true

[atoms.HELIUM]
number = 2
mass = 4.002602
symbol = "He"
name = "helium"
group = 18
diatomic = false

[atoms.LITHIUM]
number = 3
mass = 6.94
symbol = "Li"
name = "lithium"
group = 1
diatomic = false

[atoms.BERYLLIUM]
number = 4
mass = 9.0121831
symbol = "Be"
name = "beryllium"
group = 2
diatomic = false

[atoms.BORON]
number = 5
mass = 10.81
symbol = "B"
name = "boron"
group = 13
diatomic = false

[atoms.CARBON]
number = 6
mass = 12.011
symbol = "C"
name = "carbon"
group = 14
diatomic = false

[atoms.NITROGEN]
number = 7
mass = 14.007
symbol = "N"
name = "nitrogen"
group = 15
diatomic = true

[atoms.OXYGEN]
number = 8
mass = 15.999
symbol = "O"
name = "oxygen"
group = 16
diatomic = true

[atoms.FLUORINE]
number = 9
mass = 18.998403163
symbol = "F"
name = "fluorine"
group = 17
diatomic = true

[atoms.NEON]
number = 10
mass = 20.1797
symbol = "Ne"
name = "neon"
group = 18
diatomic = false

[atoms.SODIUM]
number = 11
mass = 22.98976928
symbol = "Na"
name = "sodium"
group = 1
diatomic = false

[atoms.MAGNESIUM]
number = 12
mass = 24.305
symbol = "Mg"
name = "magnesium"
group = 2
diatomic = false

[atoms.ALUMINIUM]
number = 13
mass = 26.9815385
symbol = "Al"
name = "aluminium"
group = 13
diatomic = false

[atoms.SILICON]
number = 14
mass = 28.085
symbol = "Si"
name = "silicon"
group = 14
diatomic = false

[atoms.PHOSPHORUS]
number = 15
mass = 30.973761998
symbol = "P"
name = "phosphorus"
group = 15
diatomic = false

[atoms.SULFUR]
number = 16
mass = 32.06
symbol = "S"
name = "sulfur"
group = 16
diatomic = false

[atoms.CHLORINE]
number = 17
mass = 35.45
symbol = "Cl"
name = "chlorine"
group = 17
diatomic = true

[atoms.ARGON]
number = 18
mass = 39.948
symbol = "Ar"
name = "argon"
group = 18
diatomic = false

[atoms.POTASSIUM]
number = 19
mass = 39.0983
symbol = "K"
name = "potassium"
group = 1
diatomic = false

[atoms.CALCIUM]
number = 20
mass = 40.078
symbol = "Ca"
name = "calcium"
group = 2
diatomic = false

[atoms.TITANIUM]
number = 22
mass = 47.867
symbol = "Ti"
name = "titanium"
group = 4
diatomic = false

[atoms.VANADIUM]
number = 23
mass = 50.9415
symbol = "V"
name = "vanadium"
group = 5
diatomic = false

[atoms.CHROMIUM]
number = 24
mass = 51.9961
symbol = "Cr"
name = "chromium"
group = 6
diatomic = false

[atoms.MANGANESE]
number = 25
mass = 54.938044
symbol = "Mn"
name = "manganese"
group = 7
diatomic = false

[atoms.IRON]
number = 26
mass = 55.845
symbol = "Fe"
name = "iron"
group = 8
diatomic = false

[atoms.COBALT]
number = 27
mass = 58.933194
symbol = "Co"
name = "cobalt"
group = 9
diatomic = false

[atoms.NICKEL]
number = 28
mass = 58.6934
symbol = "Ni"
name = "nickel"
group = 10
diatomic = false

[atoms.COPPER]
number = 29
mass = 63.546
symbol = "Cu"
name = "copper"
group = 11
diatomic = false

[atoms.ZINC]
number = 30
mass = 65.38
symbol = "Zn"
name = "zinc"
group = 12
diatomic = false

[atoms.GALLIUM]
number = 31
mass = 69.723
symbol = "Ga"
name = "gallium"
group = 13
diatomic = false

[atoms.GERMANIUM]
number = 32
mass = 72.630
symbol = "Ge"
name = "germanium"
group = 14
diatomic = false


[atoms.ARSENIC]
number = 33
mass = 74.921595
symbol = "As"
name = "arsenic"
group = 15
diatomic = false

[atoms.SELENIUM]
number = 34
mass = 78.971
symbol = "Se"
name = "selenium"
group = 16
diatomic = false

[atoms.BROMINE]
number = 35
mass = 79.904
symbol = "Br"
name = "bromine"
group = 17
diatomic = true

[atoms.KRYPTON]
number = 36
mass = 83.798
symbol = "Kr"
name = "krypton"
group = 18
diatomic = false

[atoms.RUBIDIUM]
number = 37
mass = 85.4678
symbol = "Rb"
name = "rubidium"
group = 1
diatomic = false




[atoms.SILVER]
number = 47
mass = 107.8682
symbol = "Ag"
name = "silver"
group = 11
diatomic = false

[atoms.TIN]
number = 50
mass = 118.710
symbol = "Sn"
name = "tin"
group = 14
diatomic = false

[atoms.IODINE]
number = 53
mass = 126.90447
symbol = "I"
name = "iodine"
group = 17
diatomic = true

[atoms.XENON]
number = 54
mass = 131.293
symbol = "Xe"
name = "xenon"
group = 18
diatomic = false

[atoms.CAESIUM]
number = 55
mass = 132.90545196
symbol = "Cs"
group = 1
diatomic = false

[atoms.BARIUM]
number = 56
mass = 137.327
symbol = "Ba"
name = "barium"
group = 2
diatomic = false

[atoms.PLATINUM]
number = 78
mass = 195.084
symbol = "Pt"
name = "platinum"
group = 10
diatomic = false

[atoms.GOLD]
number = 79
mass = 196.966569
symbol = "Au"
name = "gold"
group = 11
diatomic = false

[atoms.LEAD]
number = 82
mass = 207.2
symbol = "Pb"
name = "lead"
group = 14
diatomic = false

[atoms.FRANCIUM]
number = 87
mass = 223
symbol = "Fr"
name = "francium"
group = 1
diatomic = false
